# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 富途Cocoa开发技术博客
email: deger@futunn.com
description: > # this means to ignore newlines until "baseurl:"
  富途证券研发部Mac开发组技术博客，我们开发了大陆区Mac App Store财经类免费版、收费版第一应用－富途牛牛。
baseurl: "" # the subpath of your site, e.g. /blog
url: "futucocoa.github.io" # the base hostname & protocol for your site
github_username:  futucocoa
link1_name: "富途证券官方网站"
link1_url: "https://www.futu5.com"
link2_name: "富途牛牛下载地址"
link2_url: "https://itunes.apple.com/cn/app/fu-tu-niu-niu-gu-gang-gu-mei/id664513913?mt=12"
# Build settings
markdown: kramdown
